### ISSUE TITLE
Identifisere «baggasje» fra eksisterende regelverk, standarder og praksis som man bør kvitte seg med

### ISSUE THREAD

**Issue by herbandresen** [arkivverket/standardlab#25]
### Beskrivelse av behov

Forslagene presenteres først i en litt korthugget punktvis form, deretter følger en litt mer omstendelig forklaring og motivasjon for de ulike forslagene.

1. Svært fleksible arkivstrukturer, ingen obligatoriske hierarkier som en registrering må inngå i, og minimalt med obligatoriske metadataelementer.

2. Valgfrie arkivstrukturelementer – registreringer kan knyttes til ingen, én eller flere av ulike former for strukturerende elementer:
a)	aktører (personer og virksomheter som skaper, bruker, er parter i osv.)
b)	forløp (funksjoner, prosesser, aktiviteter, transaksjoner)
c)	beholdere eller aggregeringer («containers»), f.eks. mappe, eller objekt (bygning, tunnel, festival, kontrakt, osv.) 
d)	sporingsinformasjon (kildesystem/-prosess, signaturer, fullmaktsforhold osv.)

3. En registrering har en entydig identifisert disponeringsansvarlig (som innestår for beslutning om bevaring, overføring eller sletting av registreringen). Dette kan være en virksomhet eller en person. Et «arkiv» er den virtuelle samlingen av de registreringer som en disponeringsansvarlig innestår for, uavhengig av hvilket system registreringen befinner seg i.

4. Den enkelte registrering kan knyttes til null, ett, eller flere innholdskomponenter (dataelementer, datasett, dokumenter osv.). Det bør kunne legges opp til både innholdskomponenter som fikseres med registreringen, og innholdskomponenter som kan endres. Det må fremgå av registreringen om ett eller flere innholdskomponenter er fiksert for registreringen eller ikke. 

5. «Postjournal» for å støtte innsynsmuligheter erstattes av en oppskrift for å «mappe» intern organisering av dokumentasjonen til et generisk «einnsyns»-format. Samme registrering kan presenteres på flere ulike måter samtidig, i en eller flere egnete «einnsyns»-løsninger.

6. Kravet til gjennomgående klassifikasjonsordning (arkivforskriften § 5) avvikles. 

7. Alt kan klassifiseres, ulike vokabularer, autoritetsregistre og kodeverk osv. kan knyttes til både registreringer, innholdskomponenter og arkivstrukturelementer. Det bør kunne settes opp vokabularer både med og uten krav til å opprettholde konsistent historikk. 

8. Avleveringsformat organiseres med utgangspunkt i den enkelte registreringen, alle tilknyttede data til en registrering tas med i den enkelte registreringens avleveringsobjekt. Flere avleveringsobjekter kan legges etter hverandre i samme fil, i så fall gjentas opplysninger om f.eks. parter, mapper, eller aktiviteter osv. for hvert avleveringsobjekt.

9. Periodisering av arkiver avvikles. Den disponeringsansvarlige kan opprette avleveringsobjekt for den enkelte registrering når som helst, kanskje med en maksimal tidsfrist på en del år. Det er opp til den disponeringsansvarlige å ta stilling til egenoppbevaring, sletting eller eventuell overføring av avleveringsobjektet, herunder å beslutte om flere avleveringsobjekter skal pakkes sammen i en felles fil.

10. Godkjenning av systemer avvikles. I den grad det skulle være nødvendig å godkjenne noe, bør godkjenningen være knyttet til, og begrenset til, de virksomheter som er tilsynsobjekter etter arkivloven § 7. Spissformulert: «Arkivverket kjenner ingen systemleverandører». Godkjenninger bør dreie seg om hvor og hvordan arkivansvaret ivaretas, herunder bruken av egne eller andres systemløsninger.

Litt nærmere forklaring av og bakgrunn for forslagene over.

Til punkt 1
En registrering bør, som nå, være den grunnleggende enheten i et dokumentasjonsmiljø. Hver registrering bør ha en unik identifikator, et registrert tidspunkt for opprettelsen, og en angivelse av hvem som er disponeringsansvarlig (se punkt 3). Det som er obligatorisk bør helst ikke omfatte mer enn dette.

Det vil i praksis være behov for en god del mer metadata for at registreringen skal gi mening i ulike sammenhenger. Spørsmålet er imidlertid ikke «om det trengs noe mer», men om det er en god idé å stille nærmere krav til hva som skal være obligatorisk. Obligatoriske metadata er i realiteten et krav til å innordne arkivdanningen i bestemte strukturer. Et spørsmål som har vært opp i mange sammenhenger er om man skal standardisere virksomhetsspesifikke metadata, noe som i praksis vil innebære at man standardiserer informasjons- og prosessmodellene for ulike fagområder i forvaltningen. Det bør absolutt ønskes velkommen at fagområder som for eksempel barnevern eller skjenkebevillinger standardiseres, men det bør fagmiljøene gjøre selv. Arkivstandarders fremste bidrag kan være å holdes tilstrekkelig åpne for ulike måter å standardisere fagområdene på. Arkivstandarden bør begrense seg det som er tvingende nødvendig.

I dette punktet inngår også fjerning av obligatoriske, entydige hierarkiske trestrukturer. Det innebærer, først og fremst, at en registrering ikke bare skal kunne henge fast i én mappe. Den formen for streng hierarkisk struktur gjenspeiler ikke de sammensatte prosessene og den reelle informasjonsbehandlingen, samme registrering kan være flere ting samtidig. Enkelt eksempel: En familie søker permisjon fra skolen for sine tre barn, dette behandles som ett saksforløp, vedtak om innvilgelse (bare denne registreringen, ikke hele saksforløpet) er også en registrering i hver av de tre barnas elevmappe. Det er en upresis omvei å duplisere registreringene med krysshenvisning mellom mapper. 

Et annet og litt mer omfattende eksempel, som er omtalt i NOU 2006:5 (Norsk helsearkiv) s. 73, er at ulike deler av en konsultasjon i pasientjournalen, som kliniske vurderinger eller prøvesvar, både kan knyttes til overliggende omsorgsperiode, et behandlingsforløp, et emne, eller ett av pasientens medisinske problemer, illustrasjonen av denne situasjonen er i NOU-en illustrert med flere ulike «mapper» som henger over ulike sammensetninger av journaldokumenter. 

Til punkt 2
De fire kategoriene av valgfrie strukturerende elementer er inspirert av «records continuum»-modellen, en tenkemåte for dokumentasjon (utviklet ved Monash universitet i Australia på 90-tallet). Det er neppe noen grunn til å stille spesifikke krav til metadata eller strukturelle sammenhenger i disse elementene. Det viktigste poenget er at ikke alle kontekster nødvendigvis er kjent og forbundet med registreringen på et gitt tidspunkt. De må i seg selv være fleksible, og deler av dem må kunne kobles av eller på etter at registreringen er opprettet. 

En sentral bakgrunn for «records continuum»-tenkingen er at den utfordrer og problematiserer fikseringen av dokumentasjonen. Hva en registrering er, og hvilket innhold den har, vil selvfølgelig omfatte et (avgjørende viktig) element av en skarp tilblivelse i en bestemt kontekst på et bestemt tidspunkt, men også ofte tilførsel av nye sammenhenger senere. Det åpner også muligheter for at registreringer kan gjøres på et utkast- eller skissenivå, og ikke knyttes så sterkt til «ferdigstilt dokument» som det gjøres i dag.

For eksempel kan en virksomhet ha en enhetlig måte å registrere HMS-avvik på. På registreringstidspunktet kan det være usikkerhet om alvorlighetsgraden, f.eks. om avviket har ført til personskade, slik at man først senere vet nok om hvilken prosess for oppfølging og lukking av avviket denne registreringen hører til i. 

Til punkt 3
Ordet disponering brukes i norsk versjon av ISO 30300-serien som en oversettelse av disposition, som er det å bestemme og iverksette beslutninger om overføring, destruksjon eller (normalt tidsavgrenset) egenoppbevaring av dokumentasjon. 
Ved å angi en entydig disponeringsansvarlig – som er et attributt som kan endres ved behov – for en registrering, kan man oppnå en svært fleksibel avgrensning av hva som inngår i samme arkiv. Omfanget av et arkiv vil hverken være bundet til bestemte arkivdanningssystemer eller til at det etableres en strukturell forbindelse mellom en arkiventitet og de registreringene som inngår. 

Til punkt 4
Innholdskomponenter tilsvarer det som dekkes av arkivlovens definisjon av dokument, en «logisk avgrenset informasjonsmengde», eksempelvis en tredimensjonal digital bygningsmodell, et regnestykke, resultatet av en databasespørring, en anbudsjournal, en film, et tekstdokument, osv.

Hele eller deler av en innholdskomponent bør kunne kobles til flere ulike registreringer, uten at det dermed skal kreves at man oppretter en ny instans av innholdskomponenten.

Den vanligste forbindelsen mellom en registrering og en innholdskomponent vil, antakeligvis, være at innholdet fikseres, eller «fyses», for den bestemte registreringen. Et avsendt vedtaksdokument skal for eksempel ikke kunne endres av vedkommende forvaltningsorgan i ettertid.

Det finnes imidlertid også en del former for dokumentasjon som er, og som skal være, i utvikling etter at en registrering er opprettet. Det gjelder for eksempel anbudsjournaler, som i en viss forstand er en «journal-i-dokumentet». Det kan være situasjoner der et dokument er (eller oppfattes som) «levende». Det er imidlertid noe som antakelig bare forekommer i relativt beskjedent omfang, og det bør fremgå av registreringen at den har tilknyttet innhold som ikke er endelig fiksert på opprettelsestidspunktet, slik at et hovedprinsipp om integritetskontroll av innholdet opprettholdes for øvrig dokumentasjon.

Til punkt 5
En allment tilgjengelig støtte for innsynsforespørsler er et opplagt behov. Om man legger opp til svært få obligatoriske metadata, og at det ikke skal være obligatoriske hierarkiske arkivstrukturer, blir det lite igjen i systemene som er egnet til direkte overføring til einnsyn.no, eller til andre innsynstjenester på nett. 

Det kan man kompensere for ved å sette opp en form for «mapping» fra de metadataene som den enkelte virksomhet faktisk har, til et generisk format som egner seg for å legge over i en einnsynsløsning. For eksempel kan dokumentasjon av byggesaker gjøres tilgjengelig ved at registreringene grupperes etter eiendomsidentifikasjon, eller etter saksnummer i løpende byggesaker. Det vil for så vidt heller ikke være noe i veien for at man kan finne samme registrering i einnsyn.no både med eiendomsid og med saksid som strukturerende informasjon eller søkeinngang. 

Tesen her er at det ikke er behov for «ekte» postjournaler med obligatoriske metadata for å presentere informasjon i et søkegrensesnitt.

Til punkt 6
En gjennomgående klassifiseringsordning for et forvaltningsorgan er et krav som finnes i arkivforskriften. Dette kravet har to historiske begrunnelser. Den ene er rekkeordning for effektiv gjenfinning. Den andre er at det har vært antatt at klassifisering er et egnet utgangspunkt for bevaringsvurderinger. Det siste formålet har man aldri lykkes med å få noe ut av, det første er et behov man ikke lenger har. 

Klassifisering, i form av en strukturert analyse av hva virksomheten driver med, vil ofte være hensiktsmessig som del av arbeidet med å forstå prosessene og dokumentasjonsbehovene. For noen typer fremfinningsbehov kan det også være hensiktsmessig å kode klassifikasjonen, kanskje særlig på områder der fasettert klassifikasjon kan brukes til å filtrere en stor informasjonsmengde ned til et mindre omfang, men det er ellers lite som tilsier at det skulle være noe behov for å stille obligatoriske krav til at et klassifikasjonssystem skal dekke hele virksomheten.

Til punkt 7
Dette er et punkt om hva man kan ha til erstatning for gjennomgående klassifisering. I informasjonsbehandling har man ofte stor nytte av kontrollerte vokabularer av ulike slag, blant annet for å styre lovlige valg av verdier for et attributt, eller for å kunne henvise til ekstern kildeinformasjon. Vokabularer, referanseopplysninger og klassifikasjonskoder med videre kan være aktuelt for metadata nær sagt hvor som helst i en informasjonsmodell. 

Det finnes ulike behov for hvor historisk stabile ulike vokabularer må være. Tradisjonelt har regelen for arkivnøkler vært at man kan tilføye, men ikke fjerne eller endre, arkivkoder. Arkivkoder som ikke skal brukes lenger kan også «parkeres», men ikke fjernes. Den formen for pålitelig historikk trenger man på en del områder, som for eksempel diagnosekoder, mens det kanskje har mindre å si for eksempel for ulike kategorier av drikkevarer etter alkoholloven.

Det bør ikke stilles noen krav til hvilke vokabularer som skal brukes, men det bør kanskje være en form for angivelse av hva slags kontroll med historikken som er forutsatt for de vokabularene som brukes. 

Mange vokabularer røktes av andre virksomheter enn arkivskaperen, og da kan det være vanskelig å vite helt sikkert hvordan historikken håndteres – men det kan likevel være fornuftig at virksomheten undersøker spørsmålet, og tar stilling til hva slags historikkhåndtering de legger til grunn at gjelder for det eksterne vokabularet. Kontroll med eksterne vokabularer og kodeverk er imidlertid et notorisk usikkert område, for eksempel ble kommunesammenslåinger for et par tiår siden håndtert slik at ett kommunenummer «overlevde», mens de andre ble spist. Det «overlevende» kommunenummeret var da i realiteten noe annet enn det hadde vært før sammenslåingen. I de senere års kommunesammenslåinger har derimot nye kommuner fått nytt kommunenummer i stedet for å gjenbruke de gamle. 

Til punkt 8
En annen måte å strukturere avleveringsuttrekk på vil være nødvendig som en slags «følgeskade» av punkt 1 og 2, at man ikke har en entydig hierarkisk arkivstruktur, og at registreringene kan ha mange ulike tilknyttede kontekster. For å få innholdet med seg, må derfor all tilhørende informasjon kobles sammen med registreringen, som da utgjør et samlet avleveringsobjekt. Det vil ikke være noen holdbar måte å observere innholdet i et arkiv på «fra oven». Flere avleveringsobjekter kan for så vidt legges etter hverandre i samme fil eller filpakke, men uten at det vil være noen nødvendig rekkefølge mellom dem. Hvilke sammenhenger en registrering inngår i kan rekonstrueres ved behov, men det fremgår ikke av overføringspakken.

Nødvendigheten av å lage separate avleveringsobjekter av hver registering kan illustreres med samme eksempel som i punkt 1. I familiens søknad om permisjon fra skolen for sine barn er kanskje registreringen bare knyttet til et saksnummer for søknadsbehandlingen, mens avleveringsobjektet for vedtaksbrevet, som er en annen registrering, både vil være knyttet til samme saksnummer og til hver av de tre barnas elevmapper.

Til punkt 9
Periodisering holder en arkivdel samlet, slik at man i prinsippet kan si at arkivdelen «er enten her eller der». Det er for så vidt allerede med dagens regelverk og praksis et prinsipp med ganske store huller i. 

En avvikling av periodiseringen er en «følgeskade» av punkt 3 ovenfor. Arkivet, eller arkivdelen, er ikke lenger konkrete strukturelementer med et direkte avgrensbart underliggende innhold. 

Periodiseringen fører i praksis til at arkivdelers innhold avgrenses til systemer eller lagringsstrukturer som holder arkivdelens innhold samlet. Registreringer bør kunne ha ulike deler av sitt innhold og sine kontekstopplysninger i ulike systemer, for eksempel at saksbehandling og elevmapper foregår i ulike systemer, men likevel slik at en registrering som hører til begge steder utgjør ett samlet avleveringsobjekt.

Til punkt 10 
Kravet til å bruke godkjente systemer, i arkivforskriften § 11, er rettet til forvaltningsorganer. I praksis blir kravet til å bruke godkjente systemer ivaretatt ved at tilbyderen av systemet får en godkjenning. Det er en innretning som bygger på at vesentlige dokumentasjonsegenskaper ivaretas gjennom systemets oppbygning og virkemåte. 

Den sterke nedbyggingen av hva man bør standardisere og gi regler for, i de forslagene som er fremmet i de foregående ni punktene her, tilsier at det ikke lenger vil finnes et sett av obligatoriske krav som et arkivsystem kan godkjennes etter. I stedet vil det måtte være den samlede konfigurasjonen av systemer, prosesser og strukturer hos det enkelte forvaltningsorgan som må holde mål og gi gode nok arkiver som resultat. 

I prinsippet kunne en ordning med forhåndsgodkjenning videreføres, om den rettes mot forvaltningsorganene i stedet for å rettes mot leverandører. Det er likevel grunn til å tvile på om det er gjennomførbart, både omfanget av mulige konfigurasjoner og antallet ulike forvaltningsorganer tilsier at en slik oppgave får for stort volum. Det er antakelig mer realistisk å kvalitetssikre dokumentasjonspraksiser gjennom veiledning og tilsyn.

### Mål/motivasjon

Behovsdrevet standardisering er en god ambisjon, som det er rimelig å forstå slik at man ikke skal standardisere i større grad enn det som trengs, eller det som etterspørres. 

Likevel er det en fare for at det å melde inn behov kan få en for sterk «adderende» effekt, slik at det ikke blir en fremgangsmåte som synliggjør hva det er ønskelig og mulig å fjerne fra dagens standarder, regelverk og praksis. Den måten ting gjøres på i dag kan lett bli en form for skjult bagasje, som det ikke stilles spørsmål ved, og som man derfor tar med videre. 

Dette innspillet dreier seg om å fremme noen forslag til endringer som demonterer og skjærer bort en del av de føringene og begrensningene som ligger i dagens standard og regelverk. Disse forslagene berører ikke bare elementer i dagens Noark 5, de vil også innebære noen behov for endringer i arkivforskriften og riksarkivarens forskrift, men de forutsetter ikke at man venter på en ny arkivlov. 

### Suksesskriterier/måling

Neppe målbart

### Område/prosess

Ingenting blir enklere, men forvaltningen oppnår at samsvaret mellom det de driver med og det som dokumenteres blir bedre. 

### Målgrupper

Kanskje i første rekke fagmiljøer som jobber med å forbedre og strømlinjeforme forvaltningsprosesser innen spesifikke områder (byggesaker, barnevern, helse)

### Hastegrad

Det som ligger i overskriften, 'Identifisere «baggasje» fra eksisterende regelverk, standarder og praksis som man bør kvitte seg med', bør være på agendaen tidlig. De enkelte punktene som sådan har lav hastegrad. 

### Forslag til løsning

Må utredes

**Comment by oivkru** [comment]
Takk for innspill, dette blir svært nyttig for oss når vi skal fortsette å jobbe mer konkret med ulike behov. Vi har foreløpig ikke lagt vekt på hva som fungerer og ikke fungerer i dagens standard (og regelverk og praksis), men forsøkt å identifisere de behovene som skal løses. Når vi jobber videre med behov, må vi derimot se på hva som finnes av eksisterende standardisering (inkludert Noark, men også andre), og se hva som er hensiktsmessig å ta med videre, eventuelt i revidert form. Og jeg tenker det er her dine innspill kommer inn. 

Jeg tillater meg å prøve å tolke innspillene ved å knytte dem til ulike behov: 
Punktene 1 til 4 handler om behovet for en systemuavhengig informasjonsmodell. Vi har foreløpig omtalt dette under #21 , men det er også aktuelt for både #12   (dvs. identifisere autentisitetsstøttende metadata knyttet til et informasjonsobjekt) og #15   (selv om det er et issue som ikke nødvendigvis skal handle om uttrekksformat og struktur). Dine forslag her er nyttige i arbeidet med en ny informasjonsmodell, enten vi tar utgangspunkt i dagens modell, eller vi starter med blanke ark, og bygger opp en ny fra bunnen av. 

Hvorvidt det skal dannes en «postjournal» (punkt 5) eller ikke vil avhenge av et regelverksarbeid som er utenfor vårt mandat. Når oppgaven er å utforme nødvendig og ønsket standardisering tror vi det primært handle om å ha relevante kontekstuelle metadata. Vi må først og fremst legge til rette for fleksibel arkivering, og så kan annen bruk legges til. 

Spørsmålet om klassifikasjon (6 og 7) vil også avhenge av hva som skjer med regelverket på området. Spørsmålet for oss nå er hvilket behov det eventuelt skal løse, og hvordan standardisering kan være et virkemiddel for å støtte opp under behovet. Kanskje må vi frigjøre oss fra norsk tankegods (arkivnøkler) og ISO-standarder (funksjonsbasert klassifikasjon), i tråd med dine innspill her. Behovet er å kunne strukturere “records” på ulike måter, ut fra hva som passer den enkelte virksomhet. 

Organisering og strukturering av informasjon i ett eller flere avleveringsformat vil bli viktige tema fremover, og punkt 8 er et godt innspill her. Dette vil vi komme inn på når vi behandler #21  og/eller #15 

Hvis periodisering (punkt 9) skal være del av ny standardisering, må det også være fordi det svarer til ett eller flere identifiserte behov, og vi konkluderer med at standardisering er måten å ivareta det på. I dag handler det om å sette kontrollerte tidsskiller i et arkiv, blant annet for å skille ut eldre data, og legge til rette for arkivuttrekk og overføring.  

En diskusjon om en eventuell godkjenningsordning (punkt 10) må også komme senere. Hvilke virkemidler det vil være behov for fremover, vil blant annet avhenge av normeringsgraden, det vil si om det er en obligatorisk, anbefalt eller valgfri standard, om det er en veiledning eller en spesifikasjon, mv. For fremtidig standardisering vil dette være en viktig diskusjon når vi kommer til hvordan standardiseringen skal implementeres og overvåkes, jf. beskrivelsen av metoden vår, hvordan vi jobber med standardisering: https://github.com/arkivverket/standardlab/blob/master/styrende/metode.md
 
Noe som går igjen i flere av innspillene dine er behovet for fleksibilitet – at kravene ikke bør være strengere (mer obligatoriske) enn de trenger å være. Dette er vi helt enige med deg i, og det er en del av prinsippene vi jobber etter (selv om det ikke er så tydelig som det burde ha vært i https://github.com/arkivverket/standardlab/blob/master/styrende/maal-og-prinsipper.md).

**Comment by lvbachmann** [comment]
Takk for gode innspill, @herbandresen. Vi lukker denne da det ikke er egnet å behandle dette som behov for standardisering. Oppfølging av innspillene dine er i stor grad skissert av @oivkru.

Ang. spørsmål om utvidet prosjektgruppe: Denne vil ikke gjenoppstå, men vi vurderer å opprette en eller flere referansegruppe(r) - og da vil flere av dere som var del av utvidet prosjektgruppe være naturlige kandidater.
