### ISSUE TITLE
Minimumsinnhold for "journal eller anna registrering av metadata"

### ISSUE THREAD

**Issue by lvbachmann** [arkivverket/standardlab#4]
## Beskrivelse av behov
Arkiv som inneholder dokument underlagt journalføringsplikt følger et kravsett i dagens regelverk for hvilke metadata som **skal** finnes for hver registrering/dokument. For at nye standarder skal medføre gevinst, må det gjøres en vurdering av hvilke metadata som må være med for at et arkivuttrekk skal gi verdi.

> **Merk:** Noen relevante krav er angitt i [Arkivforskriften §10](https://lovdata.no/forskrift/2017-12-15-2105/§10). Så lenge denne er gjeldende, gir det føringer for hva resultatet av dette behovet kan være.

### Mål/motivasjon
Tydelig definisjon av **minimumsinnholdet** for metadata - dvs. de absolutte kravene for hva som må finnes. At dette er definert, vil redusere usikkerhet og sannsynlighet for at løsninger gjøres mer komplekse enn hensiktsmessig.

### Målgrupper
Utviklere av systemer (leverandører og arkivskapere). I tillegg av interesse for publikum og Arkivverket.

## Hastegrad
Lav hastegrad. Noark dekker behovet inntil videre.

**Comment by monadani** [comment]
test

**Comment by oivkru** [comment]
Eksempel på minimum metadata fra Australia: https://www.naa.gov.au/information-management/information-management-standards/australian-government-recordkeeping-metadata-standard/minimum-metadata-set

**Comment by yonyonson** [comment]
Arkivverket jobber kontinuerlig med metadata for å ivareta arkivfaglige hensyn i prosjektet "Metadata og katalog". Vi burde vurdere å gjenbruke hele eller deler av minimumsettet for metadatabehov her.
I dag er minimumsettet formet for å fungere bra for datasett som er allerede i langtidslagring, mens StandardLab jobber med datasett som er i administrativ bruk, derfor er det mulig at ikke hele miniumsettet kan brukes, men deler av det kan og, etter min mening, bør gjenbrukes og oppdateres i synk med "Metadata og katalog" arbeidet.

**Comment by sturtzel** [comment]
Ref. også ArkivLett i regi av KS m.fl.

**Comment by lvbachmann** [comment]
Merk at tittelen her henviser til en formulering i forslag til ny arkivlov. Dette behovet er neppe relevant for behandling så lenge dagens arkivlov med forskrifter er gjeldende.

**Comment by lvbachmann** [comment]
Konklusjon: Utenfor det mandatet og området StandardLab skal komme med tiltak for. Saken lukkes derfor.

**Comment by petterreinholdtsen** [comment]
[Lars Vegard Bachmann]
> Konklusjon: Utenfor det mandatet og området StandardLab skal komme med
> tiltak for. Saken lukkes derfor.

Kan dere dele med ossd en nærmere forklaring for hvorfor dette er
utenfor mandatet?  Det hadde vært nyttig lesing for å forstå hvordan
dere avgrenser problemområdet.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by lvbachmann** [comment]
Hei, @petterreinholdtsen.
Takk for at du påpeker at begrunnelsen vår er utilstrekkelig. Når vi nå har snakket en gang til om saken, og du har rett i at saken ikke burde vært lukket med den begrunnelsen vi ga. Den er dog, som nevnt i en tidligere kommentar, ikke relevant for behandling nå, siden den viser til en formulering i et lovforslag som det ennå er usikkert om vil bli gjeldende.

Vi velger å ikke åpne behovet igjen, siden vi jobber med en behovsbeskrivelse for en mer generell tilnærming til samme behov.

**Comment by petterreinholdtsen** [comment]
[Lars Vegard Bachmann]
> Takk for at du påpeker at begrunnelsen vår er utilstrekkelig. Når vi
> nå har snakket en gang til om saken, og du har rett i at saken ikke
> burde vært lukket med den begrunnelsen vi ga. Den er dog, som nevnt i
> en tidligere kommentar, ikke relevant for behandling nå, siden den
> viser til en formulering i et lovforslag som det ennå er usikkert om
> vil bli gjeldende.

Jeg forstår fortsatt ikke hvordan behovet for å detaljere innhold i
"journal eller anna registrering av metadata" er i strid med mandat
eller det standarlabben skal se på, som var det jeg håpet dere hadde et
klart svar på.

> Vi velger å ikke åpne behovet igjen, siden vi jobber med en
> behovsbeskrivelse for en mer generell tilnærming til samme behov.

Har ikke spurt om gjenåpning, da jeg ikke tror status på github-sak vil
påvirke hva som blir gjort når dere har bestemt dere for at dette ikke
er noe dere vil se på.  Var bare nysgjerring på hva som gjorde at dere
ikke ville se på dette.

Riktig og til dels mye metadata er jo en fordel for brukere av
arkivmateriale, som skal forsøke å finne frem i det som er arkivert.
Det er jo en grunn til at en sier at metadata er kjærlighetsbrev til
fremtiden.  Det kan gi mer jobb i nåtiden for å gjøre det mulig for
fremtidens brukere av arkivmaterialet å bruke arkivet.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by sturtzel** [comment]
Min erfaring er at kravet til metadata er sterkt medvirkende til manglende arkivering. Automatisk fangst fra sosiale media, e-post, chat etc. vil ikke nødvendigvis ha de metadata som Noark p.t. forventer. Via f.eks. AI kan kanskje fangsten berikes.

Jeg mener derfor at dette er et område som er vesentlig å ses på uavhengig av lovverket.

**Comment by lvbachmann** [comment]
Hei igjen, @petterreinholdtsen og @sturtzel 
Det er utenfor tvil at metadata er relevant når man skal standardisere dokumentasjonsforvaltning og arkiv. #21 er lagt til i vår behovsbacklog for å dekke relevante behov her. Vi har også delt et [dokument som beskriver mål og prinsipper](https://github.com/arkivverket/standardlab/blob/master/styrende/maal-og-prinsipper.md) (samt konsekvenser av prinsippene), som forhåpentligvis vil gjøre det litt tydeligere hva som er innenfor og utenfor mandatet vårt.
