### ISSUE TITLE
Protokoll for datautveksling for arkivformål

### ISSUE THREAD

**Issue by lvbachmann** [arkivverket/standardlab#6]
## Beskrivelse av behov
Standardisering av protokoll for utveksling av data for arkivformål mellom to aktive systemer.

Se for øvrig beskrivelsen i #5

**Comment by yonyonson** [comment]
Tilsvarende som i #5 : Vi burde se om det er protokoller som kan gjenbrukes for arkivformål, basert på eksisterende protokoller.
Vi burde også vurdere normeringsgrad her - hvor detaljert skal gi gå ned og definere alle detaljene i protokollen, og i hvilken grad vi burde referere til eksiterende standarder og spesifikasjoner.

**Comment by sturtzel** [comment]
Her er det gjennom tidene gjort mye arbeid.

Et sted å starte er det arbeidet som er gjort og fortsatt gjøres i regi av KS med flere for sammenhengende tjenester og integrasjoner.

**Comment by lvbachmann** [comment]
Slås sammen med #5
