### ISSUE TITLE
Standardlab perspektiv på mikro- eller makronivå?

### ISSUE THREAD

**Issue by solfeggietto** [arkivverket/standardlab#67]
### Beskrivelse av behov

Hvordan kan Standardlab klare å holde fokus både på mikro- og makronivå?

Mikronivå
- Behovsprioritering gjennom spørreunde mot aktuelle aktører som i detalj forklarer sine behov og utfordringer

Makronvå
- Se hele verdikjeden i arkivets livsløp i sammenheng på fra et overordnet nivå
- Fra arkivplanlegging, valg av system og leverandør, implementering, arkivdanning, vedlikehold av arkiv, planlegging av avslutning med uttrekk, pakking og innlevering, mottak depot, validering, godkjenning, rapportering, bevaring i depotforvaltningssystem og formidling (via depotforvaltningssystem eller annen vei), vedlikehold og administrasjon av depotforvaltningssystemet som Trusted Digital Repository

**Comment by lvbachmann** [comment]
@solfeggietto Hei, og takk for godt innspill. Mikronivået opplever vi at vi ivaretar godt - både gjennom aktiv behovsinnhenting og ved å ha en åpen kanal for innmelding.

Vi forsøker å ivareta makronivået ved å se de ulike behovene som spilles inn i sammenheng når vi løser dem. Eksempelvis jobber vi nå med å løse flere behov i parallell som har det til felles at de har tett sammenheng med informasjonsmodell og grensesnitt for dokumentasjonssystemer.

Det enda større makronivået - det helhetlige livsløpet for arkivinformasjon - ligger til dels utenfor StandardLabs mandat, men det er en risiko vi er veldig bevisst på. Det som skjer i arkivskapingen (innenfor vårt mandat) må fungere også for behov i senere faser.
